### ISSUE TITLE
broken icons

### ISSUE THREAD

**Issue by meelock** [Arch666Angel/angelsrefining#1]
the icons for the catalyst and artifacts, (large and small) are all broken. I can send you my mods if you want.

**Comment by Arch666Angel** [comment]
In which way are they broken?

Am 19.04.2016 um 07:47 schrieb meelock:

**Comment by meelock** [comment]
mostly all the icons are all messed up... showing bits of the ores, and lines of yellow across them and such... a few don't even have icons. I'll update (if there is an update), and see if it persists.

**Comment by Arch666Angel** [comment]
Could you post me a screenshot?

I dont know if it is related to icons as well but you could try deleting 
the crop-cache in the factorio folder, might help but I doubt it. For 
now I have no clue where this error originates.

Am 20.04.2016 um 00:37 schrieb meelock:

**Comment by meelock** [comment]
ok here are the screenshots: [http://imgur.com/fEhOJui](http://imgur.com/fEhOJui) and [http://imgur.com/pKSaSTR](http://imgur.com/pKSaSTR), hope you figure what is causing it.

**Comment by Arch666Angel** [comment]
So I have tried some things and took a look in the forums, but couldnt reproduce this on my side. My guess is that this comes from replacing icons on my side and replacing older with newer versions on your side. What you could try is: 1. Delete the crop cache in your factorio folder 2. Remove all the mods from your mods folder, start the game, let it load once, quit it and then readd the mods. Might be that factorio has to reinitialize the gfx again.

**Comment by meelock** [comment]
nope tried everything you showed me... and it still doesn't work, (I think it's because I'm on mac.)
anyway here is my [mods folder:](https://www.dropbox.com/s/zewksaku8fyl3f3/mods-meelock.zip?dl=0)... i hope you can figure out what's causing it.

**Comment by Arch666Angel** [comment]
I dont think that this is an issue with other mods, I checked something else and it might be that this is an issue with some of the icon (speacially the ones in question) having 64bit depth. If you have a graphics tool at hand you can try lowering the icons yourself to 32bit, else I will look trough them and set them all to 32bit for the next release and see if thats helping.
